name: CI  Playwright + Cucumber + Allure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}  # manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run smoke (qa)
        run: npm run test:smoke:qa
        env:
          ENV: qa
          CI: true

      - name: Generate Allure HTML
        if: always()
        run: npx allure-commandline generate allure-results --clean -o allure-report

      - name: Upload Allure HTML artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
